-- ==========================================
-- SHIELDHER DATABASE SCHEMA
-- Supabase PostgreSQL Database
-- Last Updated: 2026-02-07
-- ==========================================

-- Enable UUID extension if not already enabled
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ==========================================
-- 1. EMERGENCY CONTACTS TABLE
-- ==========================================

CREATE TABLE public.emergency_contacts (
  id TEXT PRIMARY KEY, -- Text to match app's timestamp-based ID generation
  user_id UUID REFERENCES auth.users NOT NULL,
  name TEXT NOT NULL,
  phone TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.emergency_contacts ENABLE ROW LEVEL SECURITY;

-- Policy: Users can insert their own contacts
CREATE POLICY "Users can insert their own contacts"
  ON public.emergency_contacts FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can view their own contacts
CREATE POLICY "Users can view their own contacts"
  ON public.emergency_contacts FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can update their own contacts
CREATE POLICY "Users can update their own contacts"
  ON public.emergency_contacts FOR UPDATE
  USING (auth.uid() = user_id);

-- Policy: Users can delete their own contacts
CREATE POLICY "Users can delete their own contacts"
  ON public.emergency_contacts FOR DELETE
  USING (auth.uid() = user_id);


-- ==========================================
-- 2. AUDIO RECORDINGS TABLE
-- ==========================================

CREATE TABLE public.audio_recordings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users NOT NULL,
  url TEXT NOT NULL,
  file_name TEXT NOT NULL,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.audio_recordings ENABLE ROW LEVEL SECURITY;

-- Policy: Users can insert their own recordings
CREATE POLICY "Users can insert their own recordings"
  ON public.audio_recordings FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can view their own recordings
CREATE POLICY "Users can view their own recordings"
  ON public.audio_recordings FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can delete their own recordings
CREATE POLICY "Users can delete their own recordings"
  ON public.audio_recordings FOR DELETE
  USING (auth.uid() = user_id);


-- ==========================================
-- 3. STORAGE BUCKET SETUP
-- ==========================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('audio_recordings', 'audio_recordings', true)
ON CONFLICT (id) DO NOTHING;

-- Policy: Users can upload to their own folder (folder name is user_id)
CREATE POLICY "Users can upload their own audio"
  ON storage.objects FOR INSERT
  WITH CHECK (
    bucket_id = 'audio_recordings' 
    AND auth.uid() = (storage.foldername(name))[1]::uuid
  );

-- Policy: Users can view their own audio
CREATE POLICY "Users can select their own audio"
  ON storage.objects FOR SELECT
  USING (
    bucket_id = 'audio_recordings' 
    AND auth.uid() = (storage.foldername(name))[1]::uuid
  );

-- Policy: Users can delete their own audio
CREATE POLICY "Users can delete their own audio"
  ON storage.objects FOR DELETE
  USING (
    bucket_id = 'audio_recordings' 
    AND auth.uid() = (storage.foldername(name))[1]::uuid
  );


-- ==========================================
-- 4. BUBBLES TABLE (Community Groups)
-- ==========================================

CREATE TABLE IF NOT EXISTS bubbles (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT DEFAULT 'family', -- family, trip, work, gym, school, etc.
  color TEXT DEFAULT '#E91E63',
  created_by UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  invite_code TEXT DEFAULT substr(md5(random()::text), 1, 8) UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ==========================================
-- 5. BUBBLE MEMBERS TABLE
-- ==========================================

CREATE TABLE IF NOT EXISTS bubble_members (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  bubble_id UUID REFERENCES bubbles(id) ON DELETE CASCADE,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  role TEXT DEFAULT 'member', -- 'admin' or 'member'
  joined_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(bubble_id, user_id)
);


-- ==========================================
-- 6. LIVE LOCATIONS TABLE
-- ==========================================

CREATE TABLE IF NOT EXISTS live_locations (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  speed DOUBLE PRECISION DEFAULT 0,
  heading DOUBLE PRECISION DEFAULT 0,
  is_live BOOLEAN DEFAULT false,
  is_helper BOOLEAN DEFAULT false,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ==========================================
-- 7. USER PROFILES TABLE
-- ==========================================

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE, -- For invite-by-username feature
  display_name TEXT,
  avatar_url TEXT,
  phone TEXT,
  is_helper_mode BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-- ==========================================
-- 8. ROW LEVEL SECURITY (RLS) - SIMPLIFIED
-- ==========================================

-- Note: RLS is currently DISABLED on these tables for simplicity.
-- Enable if you need stricter access control.

-- Disable RLS (current production setting)
ALTER TABLE bubbles DISABLE ROW LEVEL SECURITY;
ALTER TABLE bubble_members DISABLE ROW LEVEL SECURITY;
ALTER TABLE live_locations DISABLE ROW LEVEL SECURITY;
ALTER TABLE user_profiles DISABLE ROW LEVEL SECURITY;

-- ==========================================
-- OPTIONAL: RLS Policies (if you want to enable RLS later)
-- ==========================================

-- To enable RLS, run:
-- ALTER TABLE bubbles ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE bubble_members ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE live_locations ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Then create policies:

-- BUBBLES policies
-- CREATE POLICY "Anyone can read bubbles" ON bubbles FOR SELECT USING (true);
-- CREATE POLICY "Users can create bubbles" ON bubbles FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
-- CREATE POLICY "Bubble creators can update/delete" ON bubbles FOR ALL USING (auth.uid() = created_by);

-- BUBBLE_MEMBERS policies
-- CREATE POLICY "Users can read bubble members" ON bubble_members FOR SELECT USING (true);
-- CREATE POLICY "Users can join bubbles" ON bubble_members FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
-- CREATE POLICY "Users can leave bubbles" ON bubble_members FOR DELETE USING (auth.uid() = user_id);

-- LIVE_LOCATIONS policies
-- CREATE POLICY "Anyone can read live locations" ON live_locations FOR SELECT USING (true);
-- CREATE POLICY "Users can update their location" ON live_locations FOR ALL USING (auth.uid() = user_id);

-- USER_PROFILES policies
-- CREATE POLICY "Users can read profiles" ON user_profiles FOR SELECT USING (true);
-- CREATE POLICY "Users can update own profile" ON user_profiles FOR ALL USING (auth.uid() = user_id);


-- ==========================================
-- UTILITY: Drop all policies from a table
-- ==========================================

-- Example: Drop all policies from bubbles table
-- DO $$ 
-- DECLARE 
--     r RECORD;
-- BEGIN
--     FOR r IN (SELECT policyname FROM pg_policies WHERE tablename = 'bubbles') LOOP
--         EXECUTE 'DROP POLICY IF EXISTS "' || r.policyname || '" ON bubbles';
--     END LOOP;
-- END $$;
